[package]
name = "simple"
version = "0.1.0"
edition = "2024"

[dependencies]
antithesis_sdk = { path = "../lib", default-features = false }
serde_json = "1.0.149"


[features]
default = ["antithesis_sdk/full"]
